### ISSUE TITLE
Create a pane for viewing and scrubbing a video file

### ISSUE THREAD

**Issue by manoyes** [manoyes/subtend#4]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

A pane should be available which allows for loading, playing, and scrubbing video files.

- [ ] A button should be used to open the file
- [ ] A scrubbing timeline should be used to scrub through the video
- [ ] There should be buttons for playing/pausing, and scrubbing to the left or right in increments of 10, 5, and 1 second.

**Describe alternatives you've considered**

None.

**Additional context**

Example UI from `adriel3005/SrtEditor`:

![image](https://user-images.githubusercontent.com/1971456/155902734-a99cabf8-71b3-4f41-b26e-4a40540e29b0.png)

**Comment by adriel3005** [comment]
Errors with updated Readme. When running Setup.bat, incompatibility error pops up.

Pop up window:
![image](https://user-images.githubusercontent.com/30638262/157372178-c60ae8dc-91a0-4ac6-b925-e69783ad9c90.png)

Terminal output:
![image](https://user-images.githubusercontent.com/30638262/157372277-d8974993-6439-4953-a72f-21f6c7aef59c.png)
`Traceback (most recent call last):
  File "Setup.py", line 15, in <module>
    VulkanRequirements.Validate()
  File "E:\Github\Repos\subtend\scripts\SetupVulkan.py", line 18, in Validate
    if (not cls.CheckVulkanSDK()):
  File "E:\Github\Repos\subtend\scripts\SetupVulkan.py", line 30, in CheckVulkanSDK
    cls.__InstallVulkanSDK()
  File "E:\Github\Repos\subtend\scripts\SetupVulkan.py", line 57, in __InstallVulkanSDK
    os.startfile(os.path.abspath(vulkanPath))
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher: 'E:\\Github\\Repos\\subtend\\Subtend\\vendor\\VulkanSDK\\VulkanSDK-1.3.204.0-Installer.exe'`
